kinds = {"TASK": 0, "MEETING": 1, "MUST_BE_IN": 2}
topics = {"CN":"Course Name", "SP": "Sports", "CO": "Country Names", "TO": "General Topics", "MU": "Music Genres", "WO": "Work Related"}
DAYS = 7
HOURS = 24
QUARTERS = 4
EPOCHS=100
MIDDLE_OUT = "#1CC0DA"
MIDDLE_FIIL = "#A0E5F0"
TOP_OUT = "#C551E1"
TOP_FIIL = "#F0C4FA"
DOWN_GUI = -30
UP_GUI = 15
